增加互动视频模块
Passkou/bilibili-api pull request #189
Opened 2021-07-05 12:24 UTC by phigrey

* 互动视频继承视频类
* 重写了接口 `get_pages`, `get_download_url`
* 增加了接口 `submit_story_tree`

2021-07-05 12:37 UTC, Passkou requested changes

2021-07-05 12:37 UTC, Passkou commented on bilibili_api/interactive_video.py
> +        dict: 调用 API 返回结果
缩进

2021-07-05 12:37 UTC, Passkou commented on bilibili_api/interactive_video.py
> +        dict: 调用 API 返回结果
缩进

2021-07-05 12:37 UTC, Passkou commented on examples/best_story.py
> +from bilibili_storytree import StoryGraph, ScriptNode
例子都移到文档里头去了，这个 examples 文件夹就可以删了

2021-07-06 00:15 UTC, phigrey commented on bilibili_api/interactive_video.py
> +        dict: 调用 API 返回结果
Done

2021-07-06 00:15 UTC, phigrey commented on bilibili_api/interactive_video.py
> +        dict: 调用 API 返回结果
Done

2021-07-06 00:15 UTC, phigrey commented on examples/best_story.py
> +from bilibili_storytree import StoryGraph, ScriptNode
Done

2021-07-06 01:43 UTC, merged